/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AgiImport } from './routes/agi'
import { Route as IdImport } from './routes/$id'
import { Route as AgiIndexImport } from './routes/agi.index'
import { Route as IdIndexImport } from './routes/$id.index'
import { Route as AgiRefusjonImport } from './routes/agi.refusjon'
import { Route as AgiOppsummeringImport } from './routes/agi.oppsummering'
import { Route as AgiOpprettImport } from './routes/agi.opprett'
import { Route as AgiDineOpplysningerImport } from './routes/agi.dine-opplysninger'
import { Route as IdVisImport } from './routes/$id.vis'
import { Route as IdOppsummeringImport } from './routes/$id.oppsummering'
import { Route as IdKvitteringImport } from './routes/$id.kvittering'
import { Route as IdInntektOgRefusjonImport } from './routes/$id.inntekt-og-refusjon'
import { Route as IdDineOpplysningerImport } from './routes/$id.dine-opplysninger'

// Create/Update Routes

const AgiRoute = AgiImport.update({
  id: '/agi',
  path: '/agi',
  getParentRoute: () => rootRoute,
} as any)

const IdRoute = IdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any)

const AgiIndexRoute = AgiIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgiRoute,
} as any)

const IdIndexRoute = IdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdRoute,
} as any)

const AgiRefusjonRoute = AgiRefusjonImport.update({
  id: '/refusjon',
  path: '/refusjon',
  getParentRoute: () => AgiRoute,
} as any)

const AgiOppsummeringRoute = AgiOppsummeringImport.update({
  id: '/oppsummering',
  path: '/oppsummering',
  getParentRoute: () => AgiRoute,
} as any)

const AgiOpprettRoute = AgiOpprettImport.update({
  id: '/opprett',
  path: '/opprett',
  getParentRoute: () => AgiRoute,
} as any)

const AgiDineOpplysningerRoute = AgiDineOpplysningerImport.update({
  id: '/dine-opplysninger',
  path: '/dine-opplysninger',
  getParentRoute: () => AgiRoute,
} as any)

const IdVisRoute = IdVisImport.update({
  id: '/vis',
  path: '/vis',
  getParentRoute: () => IdRoute,
} as any)

const IdOppsummeringRoute = IdOppsummeringImport.update({
  id: '/oppsummering',
  path: '/oppsummering',
  getParentRoute: () => IdRoute,
} as any)

const IdKvitteringRoute = IdKvitteringImport.update({
  id: '/kvittering',
  path: '/kvittering',
  getParentRoute: () => IdRoute,
} as any)

const IdInntektOgRefusjonRoute = IdInntektOgRefusjonImport.update({
  id: '/inntekt-og-refusjon',
  path: '/inntekt-og-refusjon',
  getParentRoute: () => IdRoute,
} as any)

const IdDineOpplysningerRoute = IdDineOpplysningerImport.update({
  id: '/dine-opplysninger',
  path: '/dine-opplysninger',
  getParentRoute: () => IdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdImport
      parentRoute: typeof rootRoute
    }
    '/agi': {
      id: '/agi'
      path: '/agi'
      fullPath: '/agi'
      preLoaderRoute: typeof AgiImport
      parentRoute: typeof rootRoute
    }
    '/$id/dine-opplysninger': {
      id: '/$id/dine-opplysninger'
      path: '/dine-opplysninger'
      fullPath: '/$id/dine-opplysninger'
      preLoaderRoute: typeof IdDineOpplysningerImport
      parentRoute: typeof IdImport
    }
    '/$id/inntekt-og-refusjon': {
      id: '/$id/inntekt-og-refusjon'
      path: '/inntekt-og-refusjon'
      fullPath: '/$id/inntekt-og-refusjon'
      preLoaderRoute: typeof IdInntektOgRefusjonImport
      parentRoute: typeof IdImport
    }
    '/$id/kvittering': {
      id: '/$id/kvittering'
      path: '/kvittering'
      fullPath: '/$id/kvittering'
      preLoaderRoute: typeof IdKvitteringImport
      parentRoute: typeof IdImport
    }
    '/$id/oppsummering': {
      id: '/$id/oppsummering'
      path: '/oppsummering'
      fullPath: '/$id/oppsummering'
      preLoaderRoute: typeof IdOppsummeringImport
      parentRoute: typeof IdImport
    }
    '/$id/vis': {
      id: '/$id/vis'
      path: '/vis'
      fullPath: '/$id/vis'
      preLoaderRoute: typeof IdVisImport
      parentRoute: typeof IdImport
    }
    '/agi/dine-opplysninger': {
      id: '/agi/dine-opplysninger'
      path: '/dine-opplysninger'
      fullPath: '/agi/dine-opplysninger'
      preLoaderRoute: typeof AgiDineOpplysningerImport
      parentRoute: typeof AgiImport
    }
    '/agi/opprett': {
      id: '/agi/opprett'
      path: '/opprett'
      fullPath: '/agi/opprett'
      preLoaderRoute: typeof AgiOpprettImport
      parentRoute: typeof AgiImport
    }
    '/agi/oppsummering': {
      id: '/agi/oppsummering'
      path: '/oppsummering'
      fullPath: '/agi/oppsummering'
      preLoaderRoute: typeof AgiOppsummeringImport
      parentRoute: typeof AgiImport
    }
    '/agi/refusjon': {
      id: '/agi/refusjon'
      path: '/refusjon'
      fullPath: '/agi/refusjon'
      preLoaderRoute: typeof AgiRefusjonImport
      parentRoute: typeof AgiImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexImport
      parentRoute: typeof IdImport
    }
    '/agi/': {
      id: '/agi/'
      path: '/'
      fullPath: '/agi/'
      preLoaderRoute: typeof AgiIndexImport
      parentRoute: typeof AgiImport
    }
  }
}

// Create and export the route tree

interface IdRouteChildren {
  IdDineOpplysningerRoute: typeof IdDineOpplysningerRoute
  IdInntektOgRefusjonRoute: typeof IdInntektOgRefusjonRoute
  IdKvitteringRoute: typeof IdKvitteringRoute
  IdOppsummeringRoute: typeof IdOppsummeringRoute
  IdVisRoute: typeof IdVisRoute
  IdIndexRoute: typeof IdIndexRoute
}

const IdRouteChildren: IdRouteChildren = {
  IdDineOpplysningerRoute: IdDineOpplysningerRoute,
  IdInntektOgRefusjonRoute: IdInntektOgRefusjonRoute,
  IdKvitteringRoute: IdKvitteringRoute,
  IdOppsummeringRoute: IdOppsummeringRoute,
  IdVisRoute: IdVisRoute,
  IdIndexRoute: IdIndexRoute,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

interface AgiRouteChildren {
  AgiDineOpplysningerRoute: typeof AgiDineOpplysningerRoute
  AgiOpprettRoute: typeof AgiOpprettRoute
  AgiOppsummeringRoute: typeof AgiOppsummeringRoute
  AgiRefusjonRoute: typeof AgiRefusjonRoute
  AgiIndexRoute: typeof AgiIndexRoute
}

const AgiRouteChildren: AgiRouteChildren = {
  AgiDineOpplysningerRoute: AgiDineOpplysningerRoute,
  AgiOpprettRoute: AgiOpprettRoute,
  AgiOppsummeringRoute: AgiOppsummeringRoute,
  AgiRefusjonRoute: AgiRefusjonRoute,
  AgiIndexRoute: AgiIndexRoute,
}

const AgiRouteWithChildren = AgiRoute._addFileChildren(AgiRouteChildren)

export interface FileRoutesByFullPath {
  '/$id': typeof IdRouteWithChildren
  '/agi': typeof AgiRouteWithChildren
  '/$id/dine-opplysninger': typeof IdDineOpplysningerRoute
  '/$id/inntekt-og-refusjon': typeof IdInntektOgRefusjonRoute
  '/$id/kvittering': typeof IdKvitteringRoute
  '/$id/oppsummering': typeof IdOppsummeringRoute
  '/$id/vis': typeof IdVisRoute
  '/agi/dine-opplysninger': typeof AgiDineOpplysningerRoute
  '/agi/opprett': typeof AgiOpprettRoute
  '/agi/oppsummering': typeof AgiOppsummeringRoute
  '/agi/refusjon': typeof AgiRefusjonRoute
  '/$id/': typeof IdIndexRoute
  '/agi/': typeof AgiIndexRoute
}

export interface FileRoutesByTo {
  '/$id/dine-opplysninger': typeof IdDineOpplysningerRoute
  '/$id/inntekt-og-refusjon': typeof IdInntektOgRefusjonRoute
  '/$id/kvittering': typeof IdKvitteringRoute
  '/$id/oppsummering': typeof IdOppsummeringRoute
  '/$id/vis': typeof IdVisRoute
  '/agi/dine-opplysninger': typeof AgiDineOpplysningerRoute
  '/agi/opprett': typeof AgiOpprettRoute
  '/agi/oppsummering': typeof AgiOppsummeringRoute
  '/agi/refusjon': typeof AgiRefusjonRoute
  '/$id': typeof IdIndexRoute
  '/agi': typeof AgiIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$id': typeof IdRouteWithChildren
  '/agi': typeof AgiRouteWithChildren
  '/$id/dine-opplysninger': typeof IdDineOpplysningerRoute
  '/$id/inntekt-og-refusjon': typeof IdInntektOgRefusjonRoute
  '/$id/kvittering': typeof IdKvitteringRoute
  '/$id/oppsummering': typeof IdOppsummeringRoute
  '/$id/vis': typeof IdVisRoute
  '/agi/dine-opplysninger': typeof AgiDineOpplysningerRoute
  '/agi/opprett': typeof AgiOpprettRoute
  '/agi/oppsummering': typeof AgiOppsummeringRoute
  '/agi/refusjon': typeof AgiRefusjonRoute
  '/$id/': typeof IdIndexRoute
  '/agi/': typeof AgiIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$id'
    | '/agi'
    | '/$id/dine-opplysninger'
    | '/$id/inntekt-og-refusjon'
    | '/$id/kvittering'
    | '/$id/oppsummering'
    | '/$id/vis'
    | '/agi/dine-opplysninger'
    | '/agi/opprett'
    | '/agi/oppsummering'
    | '/agi/refusjon'
    | '/$id/'
    | '/agi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$id/dine-opplysninger'
    | '/$id/inntekt-og-refusjon'
    | '/$id/kvittering'
    | '/$id/oppsummering'
    | '/$id/vis'
    | '/agi/dine-opplysninger'
    | '/agi/opprett'
    | '/agi/oppsummering'
    | '/agi/refusjon'
    | '/$id'
    | '/agi'
  id:
    | '__root__'
    | '/$id'
    | '/agi'
    | '/$id/dine-opplysninger'
    | '/$id/inntekt-og-refusjon'
    | '/$id/kvittering'
    | '/$id/oppsummering'
    | '/$id/vis'
    | '/agi/dine-opplysninger'
    | '/agi/opprett'
    | '/agi/oppsummering'
    | '/agi/refusjon'
    | '/$id/'
    | '/agi/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IdRoute: typeof IdRouteWithChildren
  AgiRoute: typeof AgiRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IdRoute: IdRouteWithChildren,
  AgiRoute: AgiRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$id",
        "/agi"
      ]
    },
    "/$id": {
      "filePath": "$id.tsx",
      "children": [
        "/$id/dine-opplysninger",
        "/$id/inntekt-og-refusjon",
        "/$id/kvittering",
        "/$id/oppsummering",
        "/$id/vis",
        "/$id/"
      ]
    },
    "/agi": {
      "filePath": "agi.tsx",
      "children": [
        "/agi/dine-opplysninger",
        "/agi/opprett",
        "/agi/oppsummering",
        "/agi/refusjon",
        "/agi/"
      ]
    },
    "/$id/dine-opplysninger": {
      "filePath": "$id.dine-opplysninger.tsx",
      "parent": "/$id"
    },
    "/$id/inntekt-og-refusjon": {
      "filePath": "$id.inntekt-og-refusjon.tsx",
      "parent": "/$id"
    },
    "/$id/kvittering": {
      "filePath": "$id.kvittering.tsx",
      "parent": "/$id"
    },
    "/$id/oppsummering": {
      "filePath": "$id.oppsummering.tsx",
      "parent": "/$id"
    },
    "/$id/vis": {
      "filePath": "$id.vis.tsx",
      "parent": "/$id"
    },
    "/agi/dine-opplysninger": {
      "filePath": "agi.dine-opplysninger.tsx",
      "parent": "/agi"
    },
    "/agi/opprett": {
      "filePath": "agi.opprett.tsx",
      "parent": "/agi"
    },
    "/agi/oppsummering": {
      "filePath": "agi.oppsummering.tsx",
      "parent": "/agi"
    },
    "/agi/refusjon": {
      "filePath": "agi.refusjon.tsx",
      "parent": "/agi"
    },
    "/$id/": {
      "filePath": "$id.index.tsx",
      "parent": "/$id"
    },
    "/agi/": {
      "filePath": "agi.index.tsx",
      "parent": "/agi"
    }
  }
}
ROUTE_MANIFEST_END */
